### ISSUE TITLE
和teamviewer区别

### ISSUE THREAD

**Issue by GreenHatHG** [tiaen/sunloginclient_for_deepin#1]
请问这个和teamviewer区别是什么，虽然我不用deepin，目前在用manajro，但是还是想试下这个，因为teamviewer不能用切换工作区的快捷键

**Comment by yiwanzi** [comment]
向日葵作为本土软件使用体验，稳定性上会有优势。不过这两款软件我主要用teamviewer，因为知名度更高，需求也只是简单的远程，没有深入对比。这里有一篇两款软件的详细对比，你可以参考下。http://zhongce.sina.com.cn/article/view/4423/
